# Generated by Django 6.0.5 on 2026-05-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
