# Generated by Django 6.0.5 on 2026-05-18 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewhistory',
            name='session_key',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
