# Generated by Django 6.0.5 on 2026-05-12 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
    ]
