# Generated by Django 6.0.5 on 2026-05-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
